---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.3
  creationTimestamp: null
  name: chiacas.k8s.chia.net
spec:
  group: k8s.chia.net
  names:
    kind: ChiaCA
    listKind: ChiaCAList
    plural: chiacas
    singular: chiaca
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: ChiaCA is the Schema for the chiacas API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ChiaCASpec defines the desired state of ChiaCA
            properties:
              image:
                default: registry.gitlab.com/bbhome/helm/chia-operator/chiaca-generator:latest
                description: Image defines the CA generator image to run
                type: string
              imagePullSecret:
                description: ImagePullSecret defines an ImagePullSecret for the CA
                  generator image
                type: string
              secret:
                description: Secret defines the name of the secret to contain CA files
                type: string
            required:
            - secret
            type: object
          status:
            description: ChiaCAStatus defines the observed state of ChiaCA
            properties:
              ready:
                default: false
                description: Ready says whether the CA is ready, this should be true
                  when the SSL secret is in the target namespace
                type: boolean
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
